ktor:
  application:
    modules:
      - com.github.thorlauridsen.SampleApplicationKt.module
  deployment:
    port: 8080
app:
  database:
    url: "$DATABASE_URL:jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;"
    username: "$DATABASE_USERNAME:sa"
    password: "$DATABASE_PASSWORD:"
  liquibase:
    changelog: "db/changelog/db.changelog-master.yaml"
